### ISSUE TITLE
In mobile, reports' verification indicators are confusing 

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#101]
We have received a complaint about the mobile UI.

Reports say "Verified YES" and "Verified NO". This should change to "Verified" and "Unverified".

**Comment by mjollnir** [comment]
will look into this shortly. I guess you mean on the report page rather than the report list page.

**Comment by mjollnir** [comment]
new version of mobile plugin (closed by 000762eb5544ab3bf52529538429f872b0d97fc8)
