### ISSUE TITLE
Email notification unsubscribe links go to localhost

### ISSUE THREAD

**Issue by kayakr** [ccnz/Ushahidi_Web#109]
Return-Path: www-data@eq.org.nz
I'm subscribed to the geographical notifications via email. I notice that the unsubscribe link is malformed, e.g. http://localhost/alerts/unsubscribe/hMahrzdSpiADv3hQulS

Thanks
## Jonathan

X-Original-To: XXXXXX@jonathanhunt.org
Delivered-To: web17_jonathan@smithers.egressive.com
Received: by smithers.egressive.com (Postfix)
    id AB6F1D4272; Fri,  4 Mar 2011 08:22:27 +1300 (NZDT)
Delivered-To: web90_jonathan@smithers.egressive.com
Received: from mail3.egressive.com (unknown [202.6.116.137])
    by smithers.egressive.com (Postfix) with ESMTP id A2A43D41E9
    for <XXXXXXjonathanhunt.org>; Fri,  4 Mar 2011 08:22:27 +1300 (NZDT)
Received: from db-a.eq.org.nz (ec2-50-18-60-42.us-west-1.compute.amazonaws.com [50.18.60.42])
    by mail3.egressive.com (Postfix) with ESMTPS id A0B6C9C3EC
    for <XXXXXXjonathanhunt.org>; Fri,  4 Mar 2011 08:22:20 +1300 (NZDT)
Received: from web-a.eq.org.nz (unknown [184.72.35.29])
    by db-a.eq.org.nz (Postfix) with ESMTP id 2EFA55C110
    for <XXXXXXjonathanhunt.org>; Thu,  3 Mar 2011 19:22:16 +0000 (UTC)
Received: by web-a.eq.org.nz (Postfix, from userid 33)
    id 521BC360B5; Fri,  4 Mar 2011 08:22:08 +1300 (NZDT)
To: XXXXXXjonathanhunt.org
Subject: [Christchurch Recovery Map] Water from well - 69 Jellicoe  Street, South Brighton Domain
X-PHP-Originating-Script: 1001:MailSend.php
From: Christchurch Recovery Map eqnzfeb@gmail.com
Reply-To: Christchurch Recovery Map eqnzfeb@gmail.com
Date: Fri, 04 Mar 2011 08:22:08 +1300
X-LibVersion: 3.3.2
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit
Message-ID: 20110303192208.6967.258194104.swift@eq.org.nz
X-egressive-MailScanner: Found to be clean
X-egressive-MailScanner-From: www-data@eq.org.nz
X-Spam-Status: No

Currentat 3 Mar
http://canterburyearthquake.org.nz/water-tanker-timetable-for-deliveries/

You have received this email because you subscribed to receive alerts. If you do not wish to receive future alerts go to http://localhost/alerts/unsubscribe/hMahrzdSpiADv3hQulSt

**Comment by malclocke** [comment]
Seems to be related to the setting of `$config['site_domain']` in `application/config/config.php`

According to rcoup, this is currently set to '/' in which case the following code kicks in when determining `url::site()`:

```
# system/helpers/url.php:61
if ($site_domain === '' OR $site_domain[0] === '/')
{
  // Guess the server name if the domain starts with slash
  $base_url = $protocol.'://'.$_SERVER['HTTP_HOST'].$site_domain;
}
```

`$_SERVER['HTTP_HOST']` must be resolving to localhost.  Suggest changing `$config['site_domain']` to `eq.org.nz/'

**Comment by malclocke** [comment]
Jonathan,

Change pushed to live which should fix this.  Please mark issue closed if it works for you.

Malc

**Comment by kayakr** [comment]
Looks good now, thanks Malc.
