### ISSUE TITLE
improve visability of road closures

### ISSUE THREAD

**Issue by mjollnir** [ccnz/Ushahidi_Web#123]
Email from my sister:

The info map provided on eq.org.nz is great; showing what roads are
closed but those ones marked with red lines is too pale to be useful.
If something could be done to increase the hue in the red lines it
would really show up on the map and you'd see what is closed
immediately.
Just a small request but could help those with bad eyesight?
You're doing a wonderful job

**Comment by mjollnir** [comment]
up road closure stroke opacity to 0.8 for people with poor vision - closed by cd4a564a189cc88451f6c16278bdc6c83971f3f8

**Comment by Br3nda** [comment]
I'm adding road closures to the mapsync plugin - at least 24 hours away from having it working
