### ISSUE TITLE
Creating reports with Polygon shapes breaks the map

### ISSUE THREAD

**Issue by nigelmcnie** [ccnz/Ushahidi_Web#14]
As reported by Shiny in IRC.

Creating a report with a polygon shape on the map, then approving it, results in something similar to:

23:00 < Shiny> >application/views/admin/reports_edit_js.php [206]:
23:00 < Shiny> Trying to get property of non-object

I've looked into the issue but can't reliably duplicate it, and don't want to while it means that the maps stop working as a result.

**Comment by rcoup** [comment]
talk to chris mcdowall, he might have got this working. Need to check lines too.

**Comment by philiprenich** [comment]
Had this happen while leaving both Approve and Verify set to No.

**Comment by notgeorge** [comment]
polygons system was added in less than a week ago.  there's likely plenty of bugs in it.  david kobia's the guy responsible for that code.

**Comment by Br3nda** [comment]
seems to be fixed
there are some other bugs related to polygons, but this one can be closed
