### ISSUE TITLE
Can't use IFRAME tags in Pages

### ISSUE THREAD

**Issue by rcoup** [ccnz/Ushahidi_Web#19]
Screws up embeds.

Maybe the tip from this can help? http://www.cheyennejack.com/blog/post.cfm/mangoblog-how-to-enable-iframe-tag-in-tinymce

**Comment by sminnee** [comment]
Can you give an example URL of a page editing screen on the dev site?

**Comment by rcoup** [comment]
http://dev.eq.org.nz/admin/manage/pages

the Google people-finder has an iframe hacked in by editing the DB table directly.

**Comment by sminnee** [comment]
Fixed in 6160d95afdfa59cc487007e9b1923864ab02808e.  Not yet on dev.  (Fixes #21 on that commit was a typo sorry :-/)
