### ISSUE TITLE
Add times to *all* dates throughout

### ISSUE THREAD

**Issue by rcoup** [ccnz/Ushahidi_Web#20]
We need to change the dateformatting to include times. Having "24 Feb" is no bloody use to anyone. This is in the front & backend, I've already fixed the backend messages area

**Comment by sminnee** [comment]
Do we have some examples of where this is broken?

**Comment by rjmackay** [comment]
I see times on most of the report dates. More info?

**Comment by kshepherd** [comment]
The main page reports/news are fixed now, the only place I can see it now is in /feeds
(haven't seen any admin pages so can't comment on those)

**Comment by sminnee** [comment]
Cool, I'll fix the feeds view.

**Comment by sminnee** [comment]
Updated dates to be more consistent, using a style like &#39;13:45 Feb 24&#39;. Closed by 77990e967f86639471d55f2c4f9fe829d42e6ca3.
