### ISSUE TITLE
Mobile Site - Need to get pages working

### ISSUE THREAD

**Issue by rcoup** [ccnz/Ushahidi_Web#22]
The pages (eg. http://eq.org.nz/page/index/3) don't show up in the mobile site: http://eq.org.nz/mobile

Need the links to appear in the "More" thing too.

The mobile site is a plugin installed in /plugins/, code is from http://apps.ushahidi.com/

**Comment by sminnee** [comment]
I'm having a look at this now - should we have a custom view of each mobile page?  i.e., should we create mobile/page/index/3 with a different look & feel?

**Comment by sminnee** [comment]
Fixed mobile nav (mobile pages still don&#39;t have a proper mobile view, though). closed by 4c538bee6d460b671a1c95c6c5e9f115c90cacbf
