### ISSUE TITLE
Separate KML feed per category

### ISSUE THREAD

**Issue by rcoup** [ccnz/Ushahidi_Web#24]
We need to have some way of getting per-category KML feeds out of the site. 

KML is a plugin, see http://apps.ushahidi.org

Requested by Google, amongst others

**Comment by lordp** [comment]
I've patched the KML plugin, and put it up here -> https://github.com/lordp/ushahidi-kml-plugin

**Comment by sminnee** [comment]
Update KML module to have ?category_id=(id) filter. Closed by 72c0a88dec85b174aac56418f8e427b9ca88ab22

**Comment by rcoup** [comment]
also supports `&l=(limit)` - defaults to 100, and there's no value for unlimited, so put in a high number instead.
