### ISSUE TITLE
Ability to add external links to menubar

### ISSUE THREAD

**Issue by rcoup** [ccnz/Ushahidi_Web#28]
I'd like to add some random links to the menubar (& mobile). Not sure what the easiest/quickest way is...

**Comment by sminnee** [comment]
Riddle me this: when is a page not a page? When it's a redirector.  I think that adding some flag to the pages so that they can act as redirectors is probably a straightforward-ish way of doing this.

**Comment by sminnee** [comment]
Added REDIRECT syntax to pages so that you can add external links to menus. Closed by 0a5fb4d1198b0c32ebc515391ae3cdebf640996c
