### ISSUE TITLE
Add "unverifiable" option so that "Awaiting Verification" stream can be kept clean

### ISSUE THREAD

**Issue by noirin** [ccnz/Ushahidi_Web#30]
Some reports are never going to be possible to verify. It would really help volunteers going through the "Awaiting Verification" stream if there were a way of distinguishing these from the reports that we have not yet been able to verify, or have not yet tried to verify.

**Comment by whakkee** [comment]
me!

**Comment by mjollnir** [comment]
Merge remote branch &#39;marga/master&#39;

Merged marga&#39;s branch to closed by 3400a2ec59c27bca6b0912291292a2d334497462
