### ISSUE TITLE
Auto Report Allocator to registered responders

### ISSUE THREAD

**Issue by HE-zzz-AL** [ccnz/Ushahidi_Web#34]
Have The system set up so when a report comes in it can be automatically forwarded to a registered responder who is tagged to those types of reports. Similar to requests for help going to Student volunteer army.
E.g. Sewage complaint going to council contact for that task.
Report goes into a mailbox and when retrieved sends back a collected response. Autoquery on report requests confirmation of completion which can be date set (no. of days follow-up)

**Comment by sminnee** [comment]
Do we have an initial list of which responders should be registered for this?

**Comment by HE-zzz-AL** [comment]
We don't as yet but Civil Defence are aware of the request. Too busy to assist at moment.  This concept ties in with responder registration page and category selection for them to get reports from.  This is looking forward to when things settle into the slog of assisting people who have yet to get normality back so need extra help
