### ISSUE TITLE
Registration screen for responders to assist with specific report categories

### ISSUE THREAD

**Issue by HE-zzz-AL** [ccnz/Ushahidi_Web#35]
Page allows registration of responders to select types of reports they can assist with.
Once selected their names and contact is tagged to that category (or subcategory) this includes NGO's, civil contractors and Samaritans, commercial contractors.
Once registered they are provided with notifications of requests for assistance or problems. Once someone accepts the request the report (red status) goes into actioned (Yellow) status awaiting resolution. Once resolved a green tag is applied to the report. If unable to be actioned the report goes back to red for redistribution

**Comment by sminnee** [comment]
Is there a process currently for this, eg, an email address of a central coordinator?  How much traffic is going through this at the moment?

**Comment by HE-zzz-AL** [comment]
This has yet to be built but there is discussion on finding a way to forward on requests.
A bit like the google people finder, one side has requests and the category help is required one side registers the categories they can supply assistance. the system will match up the links
