### ISSUE TITLE
Colour coding reports

### ISSUE THREAD

**Issue by HE-zzz-AL** [ccnz/Ushahidi_Web#36]
Red = unresolved
Yellow = Actioned
Green = Resolved

Little boxes beside the report

For reports requesting assistance that is outside SVA capability

**Comment by sminnee** [comment]
I don't understand that last sentence - "For reports requesting assistance that is outside SVA capability" - which status would those reports be set to?

**Comment by HE-zzz-AL** [comment]
More technical issues that may be out of their capacity, Can't say for sure as it is like the site a dynamically moving situation. Categories will be developed out of requests.
It will help give strength to the credibility of the site if we can point to successes, but we need a way to monitor and know.

**Comment by sminnee** [comment]
I guess what I'm wondering is do we need some kind of "can't resolve" status?

**Comment by HE-zzz-AL** [comment]
unresolved stay red, which gets them more attention
