### ISSUE TITLE
KML layer problem: /undefined image links

### ISSUE THREAD

**Issue by rcoup** [ccnz/Ushahidi_Web#4]
I think KML layers are ending up with "/undefined" as their image links. Something is anyway. Presumably a Javascript object is being accessed to build the URL and it's breaking.

eg. payphones layer

**Comment by lordp** [comment]
I think this may just be that the payphone layer doesn't define an icon (or didn't), but the others did.

**Comment by kshepherd** [comment]
can somebody paste the generated KML for affected layers in this comment thread?

**Comment by noirin** [comment]
The problem with the Payphone layer was that the icon was defined with a path to an image in someone's C:\My Documents :-) Should be fixed now

**Comment by noirin** [comment]
Closing, confirmed fixed
