### ISSUE TITLE
Bug from admin user

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#45]
Hey Tim,
I'm getting this error:
Parse error: syntax error, unexpected T_VARIABLE in /var/www/eq.org.nz/plugins/mobile/hooks/mobile.php on line 42

when I go into reports to try and verify them.
Attention:
The information contained in this message and/or attachments is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender, and delete the material from any system and destroy any copies. 

This e-mail has been virus scanned and cleared by the MediaWorks NZ Ltd IT Department.

Thank you.

**Comment by sminnee** [comment]
This has been fixed - it was a temporary error that occurred when I was debugging something.
