### ISSUE TITLE
Fill landing page's third box with volunteer army link

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#61]
3rd box is blank. Let's fill it up. Please duplicate the style of the middle box with the following content:

```
Request help
Clicking on this button requests help from the Student Volunteer Army.
[Request help]
```

Button's href is http://eq.org.nz/volunteer-army

**Comment by ivanjovanovic** [comment]
Commited and deployed to dev

**Comment by mikenz** [comment]
Done in pull/59
