### ISSUE TITLE
Geocoding on the homepage doesn't work

### ISSUE THREAD

**Issue by lejoe** [ccnz/Ushahidi_Web#62]
## Steps to reproduce:
1. Go to the new homepage
2. In the "Where are you", "I am in" field, type a city that is outside of chrischurch (i.e. Rangiora)
3. It zooms the map on Christchurch instead of Rangiora
## The reasons of the bug:

The geocoder adds ',christchurch,new zealand' to make sure it looks in that irea.
## The solution:

Use the bounds instead of adding the city.

**Comment by malclocke** [comment]
Is this pushed to production?  When I type in 'New Brighton' I get taken to somewhere in Canada
