### ISSUE TITLE
Licence text - telling people what meets attribution requirements

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#64]
In the blurb at the bottom of the page after the licence is mentioned, please add the following text:

```
To satisfy attribution requirements, include "Source: http://eq.org.nz"
in your derived content.
```

**Comment by noirin** [comment]
Done

**Comment by kshepherd** [comment]
I'm fairly sure this is done in the admin UI, no patching needed.
Just add under the existing CC license and liability text

**Comment by kshepherd** [comment]
doh, too slow ;)
