### ISSUE TITLE
Missing files on dev (404s) - modernizr etc.

### ISSUE THREAD

**Issue by nigelmcnie** [ccnz/Ushahidi_Web#68]
<pre>2011/02/26 23:17:24 [error] 8810#0: *21018 open() "/var/www/js/libs/modernizr-1.6.min.js" failed (2: No such file or directory), client: 178.83.185.57, server: _, request: "GET /js/libs/modernizr-1.6.min.js HTTP/1.1", host: "dev.eq.org.nz", referrer: "http://dev.eq.org.nz/"
2011/02/26 23:17:26 [error] 8810#0: *21032 open() "/var/www/reports/js/libs/modernizr-1.6.min.js" failed (2: No such file or directory), client: 203.97.100.92, server: _, request: "GET /reports/js/libs/modernizr-1.6.min.js HTTP/1.1", host: "dev.eq.org.nz", referrer: "http://dev.eq.org.nz/reports/submit"
2011/02/26 23:17:27 [error] 8810#0: *21033 open() "/var/www/media/js/theme/default/style.css" failed (2: No such file or directory), client: 203.97.100.92, server: _, request: "GET /media/js/theme/default/style.css HTTP/1.1", host: "dev.eq.org.nz", referrer: "http://dev.eq.org.nz/reports/submit"
</pre>

**Comment by dotherightthing** [comment]
- link to /js/libs/modernizr-1.6.min.js removed from theme header earlier today (by me)
- default style.css removed from header by mikenz yesterday afternoon

Checked page header HTML and asset requests in Firebug and neither of these files are being requested so this issue should be resolved now.

**Comment by nigelmcnie** [comment]
I haven't seen any requests for them in the logs since deploying the new stuff, so I'm happy.
