### ISSUE TITLE
404s reported by nginx

### ISSUE THREAD

**Issue by norbu09** [ccnz/Ushahidi_Web#7]
the following 404s are showing up in the nginx error log:
- /var/www/media/js/theme/default/style.css
- /plugins/kml/views/circle_borderie.gif

**Comment by serenecloud** [comment]
The plugins and theme have been reworked. I can't check dev as I don't have an account - is it happening there?

**Comment by timClicks** [comment]
This has probably been fixed in the last two days. @norbu09, please reopen if you can replicate on the current site.
