### ISSUE TITLE
(mobile) Recent Reports and Related News "View More"

### ISSUE THREAD

**Issue by kampf** [ccnz/Ushahidi_Web#70]
On dev mobile there are no options to view more items in the Recent Reports and Related news queues, unlike on dev main.

Might be resolved by adding a static final list item which links to the full list of Reports and News, or that list at the point of the last item in the respective list.

**Comment by mjollnir** [comment]
oh i inadvertently fixed this without realising there was an issue for it. The related news/recent reports stuff was on the category page, I just moved it back to the homepage, under the location stuff.

**Comment by mjollnir** [comment]
closing - on dev now.
