### ISSUE TITLE
(Mobile) Reports Category Name Consistency

### ISSUE THREAD

**Issue by kampf** [ccnz/Ushahidi_Web#81]
"Goods /Supplies" needs to be corrected with extra space

A consistent first-letter capitalization would be nice.  There are multiple instances of some inconsistencies:

"Evacuation zone"
"Hardware Store"
"General shops"
"animal issues"
"Public Toilets"
"Public phone"

Suggest first-letter capitalization in all cases save for "and" "or", and where proper.

**Comment by mjollnir** [comment]
Do you mean on the category page, eg: http://eq.org.nz/mobile/categories/ ? Because as far as I can see, it's exactly the same as the list on http://eq.org.nz/

**Comment by kampf** [comment]
Yes, as a matter of fact it is.  Apologies for making this a mobile issue, as it should have been a general issue.

**Comment by mjollnir** [comment]
oki, do you want to open a general issue then and we'll close this one? just for clarity.  thanks! :)

**Comment by kampf** [comment]
Done.
