### ISSUE TITLE
Please remove could we have the "Christchurch Recovery Map" removed from pages

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#82]
In the mobile site's UI, the "Christchurch Recovery Map" headings dominate. I think they're distracting and would like them removed. Please keep the text within the `<title>`, however.

**Comment by rjmackay** [comment]
Removed the h1 from header template in ushahidi-plugins-mobile - pull request here: https://github.com/ccnz/ushahidi-plugins-mobile/pull/1

**Comment by rjmackay** [comment]
This is fixed and live. Please close the issue
