### ISSUE TITLE
Multipart SMS

### ISSUE THREAD

**Issue by ibeardslee** [ccnz/Ushahidi_Web#84]
Finding that the SMS queue has multiple messages from the same number as people go beyond the 160 character limit of the SMS.

These messages are usually within a minute of each other (although can be longer depending on the network load). They may also arrive out of sequence.

It would be good if SMS message queue was able to group the messages from the same number in a way that is easy to recognise that the messages are from the same number (and that they are within a time frame that recognises they are part of the same multipart message).  

Options that go through my head ..
1/ Group them as part of the same check box (ideal)
2/ Colour the messages from the same number the same (different from the rest).

From the site admin side of things, may want to put some way of defining the time frame that messages can be considered part of the same message (that'd be dependant on knowledge of network load).

May have issues as people act on and delete a message before the rest of the message arrives.  So maybe an admin setting of time before a message appears (or can be acted on) while waiting for multipart messages (duplicates).

People sometimes also send the same message multiple times, especially in a panic. And sometimes the network can deliver the same message multiple times.  Linking those messages will reduce the number of duplicate actions taken or logged.

**Comment by mikenz** [comment]
If the UDH header is still intact then we should be able to reassemble them?

**Comment by sminnee** [comment]
I can't tell if we're using the frontlinesms plugin or the smssync plugin, but in either case it doesn't look like we're passed the UDH data from the upstream SMS handler.

I'm not sure whether we can add smarts to the upstream provider (is this Catalyst-provided?) but if not maybe a heuristic joining of SMSes is the best way to go.

**Comment by Br3nda** [comment]
The sms gateway we use does not support multi part SMS.

**Comment by timClicks** [comment]
closing, wont fix
