### ISSUE TITLE
Flickr feed of #eqnz

### ISSUE THREAD

**Issue by timClicks** [ccnz/Ushahidi_Web#9]
Be a nice touch to add more photos

**Comment by rjmackay** [comment]
Do you mean a pushing photos from eq.org.nz into flickr? or pulling from flickr into eq.org.nz?

**Comment by timClicks** [comment]
I would like thumbnails from flickr on eq.org.nz. Red dots are great, but the look a little like measles.

**Comment by noirin** [comment]
I've recently added the stuff.co.nz images layer requested in #17 - what do you think?

**Comment by timClicks** [comment]
#17 seems fine. closing ticket.
