### ISSUE TITLE
prominently mark old reports as old

### ISSUE THREAD

**Issue by Br3nda** [ccnz/Ushahidi_Web#91]
Reports more than 24 hours old are often incorrect unless reviewed recently.

I'd like for big text to warn people that the report of a traffic jam heading north is actually 3 days old.

**Comment by hayatoc** [comment]
Or maybe just a "new" icon for new ones?

**Comment by Icondog** [comment]
The APRS protocol calls for graying of icon when information becomes stale. This is much overlooked in so called EM software applications. The protocol also will overwrite previous information.

**Comment by Br3nda** [comment]
Is it in the protocol? I saw APRS greying as client side only.
